- hosts: media
  vars:
    # not used yet
    cas_dir    : /srv/cas/
    code_dir   : /srv/crates/
    mapper_dir : /srv/crates_mapper/

  environment:
    # required for DB operations
    DJANGO_SETTINGS_MODULE=neocrates.production_settings

  tasks:
    - apt: name={{ item }} state=present update_cache=yes
      sudo : yes
      with_items:
        - nginx
        - uwsgi
        - python
        - python-dev
        - python-pip

    - name: Install python dependencies (no virtualenv used yet TODO)
      pip:  requirements=../requirements.txt

    - name: write the nginx config file
      copy: src=nginx.conf dest=/etc/nginx.conf
      notify:
        - restart nginx

    - name: write uwsgi conf
      template: src=uwsgi.conf dest=/srv/uwsgi.conf
      notify:
        - restart uwsgi


    - name: Copy crates code

    - name: Collect static
      command: python manage.py collectstatic --noinput
      chdir: "{{code_dir}}"

    - name: Migrate database
      command: python manage.py migrate --noinput
      chdir: "{{code_dir}}"

    - name: uwsgi should start at boot
      service: name=uwsgi state=started enabled=yes

    - name: nginx should start at boot
      service: name=nginx state=started enabled=yes


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart uwsgi
      service: name=uwsgi state=restarted



