- hosts: media
  sudo: yes
  vars:
    # not used yet
    cas_dir    : /srv/cas/
    code_dir   : /srv/crates/
    static_dir : /srv/static/
    mapper_dir : /srv/crates_mapper/
    fqdn       : crates.local

  environment:
    # required for DB operations
    DJANGO_SETTINGS_MODULE : neocrates.production_settings
    NODE_ENV               : production

  tasks:
    - apt: name={{ item }} state=present update_cache=yes
      with_items:
        - nginx
        - uwsgi
        - python
        - python-dev
        - python-pip
        - nodejs

    # the nodejs shipped with 14.04 is broken*
    - name: Fix nodejs
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

    # the pip shipped with 14.04 is broken*
    - name: Fix pip
      command: easy_install -U pip

    # *what happened, ubuntu?

        #- name: Crates code
        #copy: src=.. dest={{code_dir}} owner=www-data group=www-data
    - git: repo=https://github.com/naggie/crates.git
            dest={{code_dir}}
            version=HEAD
            depth=1

    - name: Install python dependencies (no virtualenv used yet TODO)
      pip:  requirements={{code_dir}}/requirements.txt

    - name: NPM for JS bundler dependencies
      npm: path="{{code_dir}}"

    - name: Build JS bundle
      command: node ./build_client_js_bundle.js
      args:
        chdir: "{{code_dir}}"

    - name: Collect static
      command: python manage.py collectstatic --noinput
      args:
        chdir: "{{code_dir}}"

    - name: write the nginx config file
      copy: src=nginx.conf dest=/etc/nginx.conf
      notify:
        - restart nginx

    - name: write uwsgi ini
      template: src=uwsgi.ini dest=/srv/uwsgi.ini
      notify:
        - restart uwsgi

    - name: Migrate database
      command: python manage.py migrate --noinput
      args:
        chdir: "{{code_dir}}"

    - name: uwsgi should start at boot
      service: name=uwsgi state=started enabled=yes

    - name: nginx should start at boot
      service: name=nginx state=started enabled=yes


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart uwsgi
      service: name=uwsgi state=restarted



